version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/services/analytics"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/services/catalog"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/services/dashboard"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/services/inventory"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/services/notification"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/services/orders"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/services/payment"
    schedule:
      interval: "weekly"
