default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=500']

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.108
    hooks:
      - id: checkov
        args:
          - --framework
          - dockerfile,secrets
          - --compact
          - --quiet
