kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devsecops-cluster
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    image: kindest/node:v1.29.2
    extraPortMappings:
      - containerPort: 30086
        hostPort: 8086
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            enable-admission-plugins: NodeRestriction,PodSecurity
  - role: worker
    image: kindest/node:v1.29.2
  - role: worker
    image: kindest/node:v1.29.2
